### ISSUE TITLE
PnL Calc

### ISSUE THREAD

**Issue by personal-coding** [Kostis-S-Z/trading-rl#5]
I forked your repo and added my EUR-USD dataset (this is hourly vs. 4-hours in your paper). I tested the code:

The reward is increasing by epoch
The test reward is quite large
But, when I try to compare the PnL, the result is a large negative
I grabbed hourly EUR-USD data from 2010-2018, using 2010-2017 as training and 2018 as testing. I've uploaded my results in my fork, data under the Data folder, and raw data under the Dataset folder.

The PnL comparison is under the Dataset folder as well. Could you take a look and see if my logic is wrong regarding the PnL? Essentially, I am looking at the action taken by the agent and assuming the action is taken at the end of the tick (i.e. buy or sell short at the end of the tick).

Thanks,
Yuri

**Comment by Kostis-S-Z** [comment]
Hi Yuri,
It is hard to say where the problem might be. The data could be a big factor in order to make sure there are no missing values or some kind of preprocessing is done. I would also suggest you to first try with 4-hour samples and then move to hourly, since the latter are much more volatile and noisy. Then, it is also important to note how you calculate the PnL. For example, in the paper we note: "the agent never exits the market, i.e., the stay action corresponds to maintaining the latest open position (either long or short), while simply avoiding updating its internal price trend." Also you can check what is your PnL for zero commission fees in order to make sure that your agent does learn a strategy but fails to adapt when a fee is introduced. Due to my heavy workload it is very difficult for me right now to spend time debugging the code in your repo since as I said the problem might be in various places, I hope you understand.
